### PR TITLE
Add notebook evaluating timing of make_gaussian_sources

### PR DESCRIPTION
**Pull request by patti**
This notebook evaluates the execution time for photutils.datasets.make_gaussian_sources as a function of the image size and the number of sources. It also generates a plot to visualize the results. This is a step toward proper benchmarking with asv. 

See http://nbviewer.ipython.org/github/patti/photutils-benchmarks/blob/master/notebooks/make_gaussian_sources-timing.ipynb

### CODE REVIEW

**Comment by patti** [comment]
@cdeil @adonath  This looks much better now. The time scales linearly with N-sources and exponentially with image size.

**Comment by cdeil** [comment]
@patti - Nice, thanks!

Why do the results look better now ... what did you change?

You say time scales exponentially with image size.
Naively (not taking RAM / cache bandwidth into account) I would have expected time to scale linearly with number of sources and pixels, because basically you evaluate the model for every source on every pixel.
Maybe plotting time / n_sources / n_pix would clearly show if this is the case (should be a constant flat line everywhere)?

@astrofrog mentioned via email that he'd prefer to not have notebooks in this `photutils-benchmarks` repo.

@patti – would you mind closing this pull request and instead starting a repo under your account (maybe call it `astropy-model-rasterize-experiments` or something)?
@astrofrog – Does this count as Patti's PR then or should we merge this here so that it counts for the GSoC application requirement by the PSF?

**Comment by patti** [comment]
@cdeil The PSF doesn't require the PR to be merged, but it should stay open for the application period. The only real change was to remove the multiprocessing, so that must have been the problem.

**Comment by astrofrog** [comment]
@cdeil - sorry, just to clarify, this specific notebook is fine in this repository because it is doing time benchmarks of functionality that is in photutils. I meant that if you had other notebooks that were related to models, etc. they should be in another repository. Does that make sense?

We don't have to merge it before the deadline but we can if it's ready :)

**Comment by bsipocz** [comment]
@cdeil - I wonder whether asv can pick up notebooks, too? Wouldn't it make sense to copy the working code to a normal '.py' file and have it in as the other benchmarks?

**Comment by astrofrog** [comment]
@bsipocz - I agree that I think we should also add this (for a few typical settings) as a benchmark in the normal asv folder - though I don't think there's any harm in also keeping the notebook, since asv doesn't really allow for a nice 2d visual representation of the time take versus multiple parameters at the moment.

**Comment by patti** [comment]
@cdeil Every source is evaluated at every pixel, so the time would scale as the number of sources ^ number of pixels. Does that make sense? It's late here, so my brain is about to turn off for the next 8 hours. 

@bsipocz I can just export the notebook as a .py if that's desired. The notebook is kind of a cool way to just see what's going on for a simple demo like this. 

@astrofrog I want to change the mean time to the min time so don't merge just yet.

**Comment by bsipocz** [comment]
@astrofrog - This must trigger a feature request to asv then ;)

**Comment by cdeil** [comment]
@bsipocz @astrofrog - In my experience `asv` is not something that you learn in an hour and that just works out of the box. So I'd prefer @patti  to focus on her [GSoC application](https://github.com/astropy/astropy/wiki/GSoC-2015-Application-Patti-Carroll:-Efficient-Modeling-Fitting-and-Image-Rasterization), the deadline is tomorrow.

This notebook and plot is exactly what I had in mind ... great job!

Now one huge speed improvement would be to only evaluate the model on bounding boxes where the model actually contributes ... there's other speed improvements and benchmarking I'd like @patti to explore ... but for her GSoC and not now. :-)

**Comment by astrofrog** [comment]
@patti - we need to add a README to this repo, but basically the repo is intended to be used with the asv tool:

http://spacetelescope.github.io/asv/using.html

which collects the tests in `benchmarks` and then runs them all multiple times to profile them. We then get this website:

http://www.astropy.org/photutils-benchmarks/

However, I have no objections to also including notebooks in the repository such as the one you show here, since indeed is a nice and different way to explore the performance.

So my suggestion is that in a separate PR, after the GSoC deadline, one of us should also add a test of make_gaussian_sources in `benchmarks`, but exporting the notebook as .py will not be enough because the benchmarks for asv have to be written in a very specific way.

**Comment by cdeil** [comment]
Note that asv very recently introduced [parametrised benchmarks](http://spacetelescope.github.io/asv/writing_benchmarks.html#parameterized-benchmarks), this is something that could be used here.

But my opinion on `asv` is that it's useful to catch performance regressions ... developing fast methods and code in the first place is much simpler via an IPython notebook.

**Comment by astrofrog** [comment]
And just to add to what I said above, what is here is great and indeed I agree with @cdeil that this kind of investigation and asv are complementary.

**Comment by bsipocz** [comment]
@cdeil - Sure, I didn't mean to do it now either. Somehow I've just assumed that this whole package is picked up by asv, and notebooks lived in my mind for tutorials and docs only (haha, I guess I can be sometimes a bit old fashioned).

**Comment by cdeil** [comment]
@patti - Maybe you could add two sentences at the top in the PR description what this is: a first investigation how fast Astropy model rasterisation is.
Other Astropy devs will look at this when they look at your application and they should be able to understand what this is by reading only the description at the top.

**Pull request closed without merging**
